alias kubectl='microk8s kubectl'
alias k='kubectl'
alias kall='microk8s kubectl get all --all-namespaces'
alias kpods='microk8s kubectl get po --all-namespaces'
alias ksvcs='microk8s kubectl get svc --all-namespaces'
